apiVersion: v1
kind: Service
metadata:
  name: redis-svc 
  namespace: roboshop
  labels:
    project: roboshop
    component: redis
    environment: dev
    tier: database
    code: redis-roboshop-dev
spec:
  selector:
    code: redis-roboshop-dev
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379