pipeline {
    agent {
        label 'agent-1-label'
    }

    environment {
        project = 'roboshop'
        env_name = 'dev'
        tier = 'database'
        component = 'mongodb'
        acc_id = '343430925817'
        region = 'us-east-1'
        label = 'agent-1-label'
        appversion = ''
    }

    options {
        ansiColor('xtrem')
        disableConcurrentBuilds()
        timeout(time: 30, unit: 'MINUTES')
        timestamps()
    }

    parameters {
        string(name: 'SNOW_CR', defaultValue: '', description: 'Please provide the snow change request')
        choice(name: 'environment', choices: ['dev', 'staging', 'qa', 'uat', 'prod'], description: 'please choose the environment')
        booleanParam(name: 'Build_Image', defaultValue: false, description: 'please check the box to build the image')
        booleanParam(name: 'Deploy', defaultValue: false, description: 'please check the box to deploy')
    }

    stages {
        stage('read the version') {
            
            steps {
                script {
                    
                    def packagejson = readJSON file: '05-catalogue/CI/scripts/package.json'
                    appversion = packagejson.version
                    echo "app version is ${appversion}"
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                script {
                    sh """
                        cd 05-catalogue/CI/scripts/
                        npm install
                    """
                }
            }
        }

        stage('Unit Tests') {
            steps {
                script {
                    sh """
                        echo "Unit tests are created by developers, we will configure the command like npm test"
                    """
                }
            }
        }
        
        stage('Sonar Qube') {
            environment {
                SCANNER_HOME = tool 'sonar-7.0'
            }

            steps {
                withSonarQubeEnv('sonar-7.0') {
                    dir('05-catalogue/CI') {
                        sh """
                            ls -la
                            $SCANNER_HOME/bin/sonar-scanner
                        """
                    }
                }
            }
        }

        // stage('Quality Gate') {
        //     steps {
        //         timeout(time: 10, unit: 'MINUTES') {
        //             waitForQualityGate abortPipeline: true
        //         }
        //     }
        // }

        stage('Build the image') {
            when {
                expression {
                    params.Build_Image
                }
            }
            steps {
                dir('05-catalogue/CI') {
                    script {
                        withAWS(region: 'us-east-1', credentails: 'aws-auth')
                            sh """
                                aws ecr get-login-password --region ${region} | docker login --username AWS --password-stdin ${acc_id}.dkr.ecr.${region}.amazonaws.com

                                docker build -t ${acc_id}.dkr.ecr.${region}.amazonaws.com/${project}-${params.environment}/${component}:${appversion} .

                                docker push ${acc_id}.dkr.ecr.${region}.amazonaws.com/${project}-${params.environment}/${component}:${appversion}           
                            """
                    }
                }
            }
        }

        stage('Trigger Deploy') {
            when {
                expression {
                    params.Deploy
                }
            }
            steps {
                script {
                    build job: "${component}-CD", parameters: [string(name: 'image_version', value: "${appversion}"), string(name: 'Deploy_to', value: "${params.environment}")]
                }
            }
        }

    }

    post {
        always {
            echo "this run always "
            deleteDir()
        }
        success {
            echo "this run only when success"
        }

        failure {
            echo "this run only when failure"
        }
    }
}