apiVersion: apps/v1
kind: Deployment 
metadata:
  name: cart 
  namespace: roboshop
  labels:
    project: roboshop
    component: cart
    environment: dev
    tier: backend
    code: cart-roboshop-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      code: cart-roboshop-dev
  template:
    metadata:
      labels:
        project: roboshop
        component: cart
        environment: dev
        tier: backend
        code: cart-roboshop-dev
    spec:
      containers:
      - name: cart-pod
        image: "{{ .Values.deployment.image_url }}:{{ .Values.deployment.image_version }}"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: cart-configmap