apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    component: frontendroboshop
    environment: dev
    tier: frontend
    code: frontend-roboshop-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      code: frontend-roboshop-dev
  template:
    metadata:
      labels:
        project: roboshop
        component: frontendroboshop
        environment: dev
        tier: frontend
        code: frontend-roboshop-dev
    spec:
      volumes:
      - name: nginx-conf
        configMap:
          name: frontend-nginx-configmap
          items:
          - key: nginx.conf
            path: nginx.conf
      containers:
      - name: frontend-pod
        image: "{{ .Values.deployment.image_url }}:{{ .Values.deployment.image_version }}"
        ports:
        - containerPort: 8079
        imagePullPolicy: Always
        volumeMounts:
        - name: nginx-conf 
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true


        
