apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: roboshop
  labels:
    project: roboshop
    component: frontendroboshop
    environment: dev
    tier: frontend
    code: frontend-roboshop-dev
spec:
  selector:
    code: frontend-roboshop-dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8079