apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-configmap 
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    environment: dev
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb-svc:27017/catalogue"
