apiVersion: v1
kind: ConfigMap
metadata: 
  name: rabbitmq-configmap 
  namespace: roboshop
  labels:
    project: roboshop
    component: rabbitmq
    environment: dev
    tier: backend
    code: rabbitmq-roboshop-dev
data:
  RABBITMQ_DEFAULT_USER: roboshop
  RABBITMQ_DEFAULT_PASS: roboshop123